### ISSUE TITLE
concensus on graph edges

### ISSUE THREAD

**Issue by raokrutarth** [raokrutarth/manufacturing-os#15]
Make sure the correct edges are formed at the end of the phase 1 protocol where all nodes have agreed on what they consume and what they produce.

**Comment by raokrutarth** [comment]
assumes the leader is already known. e.g. lowest PID is the leader

**Comment by raokrutarth** [comment]
bootstrap stage from doc.

**Comment by raokrutarth** [comment]
use/read the dict to make the worker nodes connect to the right nodes. 

This is a prereq for @chuanqichen.

**Comment by raokrutarth** [comment]
i.e. the logic to query the graph and and maintain an in-memory list of ip addresses and ports.

**Comment by AndrejSafundzic** [comment]
100 nodes lying there 
-> create the adjacency list
-> create initial flow
----
maximum utilization of base product

**Comment by AndrejSafundzic** [comment]
## Basecase returns differen blueprints.
## Have all requirements that makes sense! -> A req b, C req b
## 1. Create a cluster usign nodes.SingleItemNodes
## 2. Create a function that creates the edges in the shared dictionary

**Comment by AndrejSafundzic** [comment]
Next Step:
Create bootstrap 
	-> Leader: this is what we are doing
	-> ask for ack
	-> if not an ack
	-> recompute

**Comment by raokrutarth** [comment]
needs to be added to cluster wide flow using the flow APIs added in PR #41

**Comment by AndrejSafundzic** [comment]
Goal: Everyone is sending messages according to the flow
1. Creation function that ClusterWideFLow from a Cluster Class in initial_flow()
2. You can print out the current flow -> __repr__ -> log.debug(cluster_flow_obj)
3. Dependencies are in the Node subclass.
