### ISSUE TITLE
Unittest with random kills 

### ISSUE THREAD

**Issue by raokrutarth** [raokrutarth/manufacturing-os#16]
Kill processes (i.e. nodes) and verifying the right supply chain graph was constructed. 

![image](https://user-images.githubusercontent.com/8570223/80559619-024cb200-8993-11ea-8d2f-90fb1f8291be.png)

**Comment by raokrutarth** [comment]
Is leader election and edge agreement a prereq?
![image](https://user-images.githubusercontent.com/8570223/80559818-b9492d80-8993-11ea-82f4-ae425c265e3d.png)

**Comment by raokrutarth** [comment]
test1: only one leader.
test2: graph is as in the diagram.

**Comment by nishantrai18** [comment]
Reopening since my commit is related - but not closure for this. It has potentially relevant code though - up to @AndrejSafundzic 's judgement what to reuse and how exactly to implement this.
