### ISSUE TITLE
setup http hello & ack

### ISSUE THREAD

**Issue by raokrutarth** [raokrutarth/manufacturing-os#3]

**Comment by raokrutarth** [comment]
- Implemented sockets.

**Comment by AndrejSafundzic** [comment]
- start_process(process_id, init_inventory): each process having a server & client
- sending: hello + ack

**Comment by AndrejSafundzic** [comment]
**Basic Setup**
- 5 Servers: representing the whole system 
- 2 Clients: Representative of stage in the supply-chain (both consumers down-stream, producers up-stream)
---
**Basic Communication**:
- Client -- another Python Program
- If not leader, just returns IP of the leader
- If the leader, it does the operations.
----
- The first node the client talks to is the leader
- If leader dies, client won't be able to
