### ISSUE TITLE
Data representation on disk - Persistance

### ISSUE THREAD

**Issue by raokrutarth** [raokrutarth/manufacturing-os#4]
WAL or other persistent storage mechanism

**Comment by raokrutarth** [comment]
description of task: how will data be persisted by each process so it can handle resrarts?

Json

    corruption during restart.

WAL

    versioning of parts?
    I.e. what if a new field needs to be added to the representation of a part.
        needed only during migration?

**Comment by raokrutarth** [comment]
investigate WAL library in python

**Comment by chuanqichen** [comment]
Evaluate multiple WAL python library and this one is the best. 
https://github.com/untitaker/python-atomicwrites

**Comment by raokrutarth** [comment]
not needed so far. using the distributed raftos dict.
