### ISSUE TITLE
Broadcasting Messages

### ISSUE THREAD

**Issue by AndrejSafundzic** [raokrutarth/manufacturing-os#43]
Hi Nishant,

we made some changes and now the nodes are receiving messages. However, just one node receives the message, i.e. it is not broadcasting. Can you try to figure it out?

1. Go to branch "fix-on-wire"
2. Run main method -> you should see the following thing
`DEBUG [09:22:23 - processes.py:76 - run] subscriber in 1 got message b'\x80\x03cmessage'...
DEBUG [09:22:23 - processes.py:154 - onMessage] Received: <messages.AllocateReq object at 0x0000014DF9897898> from 0::[] -> 
DEBUG [09:22:23 - processes.py:76 - run] subscriber in 2 got message b'\x80\x03cmessage'...
DEBUG [09:22:23 - processes.py:154 - onMessage] Received: <messages.AllocateReq object at 0x0000014DF9861470> from 1::[] -> 
DEBUG [09:22:23 - processes.py:76 - run] subscriber in 3 got message b'\x80\x03cmessage'...
DEBUG [09:22:23 - processes.py:154 - onMessage] Received: <messages.AllocateReq object at 0x0000014DF9861470> from 2::[] -> 
DEBUG [09:22:23 - processes.py:76 - run] subscriber in 4 got message b'\x80\x03cmessage'...
DEBUG [09:22:23 - processes.py:154 - onMessage] Received: <messages.AllocateReq object at 0x0000014DF9861470> from 3::[] -> 
DEBUG [09:22:23 - processes.py:76 - run] subscriber in 0 got message b'\x80\x03cmessage'...
DEBUG [09:22:23 - processes.py:154 - onMessage] Received: <messages.AllocateReq object at 0x0000014DF9897C88> from 4::[] ->`

It is like a round trip
1. 1 received from 0
2. 2 received from 1
3. 3 received from 2
4. 4 received from 3
5. 0 received from 4

We used zmq.PUSH & zmq.PULL instead of zmq.REQ and zmq.REP because that made the nodes receive stuff in the first place. Before, messages weren't received. See explanation here:
https://stackoverflow.com/questions/57451774/python-zmq-responder-not-receiving-message
-> If you use REQ / REP and there is no subscriber, the messages are dropped right away.

I hope this helps! Goal: Make the message broadcast

**Comment by raokrutarth** [comment]
PUSH/PULL is for multiple nodes, *single* consumption.
REQ/REP: traditional server and client. 
PUB/SUB: send to all. (may not be ideal for heartbeat request and acks)

**Comment by raokrutarth** [comment]
done as of now with `drop message id dest != self.node_id`
