### ISSUE TITLE
Add support to manipulate raftos replicated containers

### ISSUE THREAD

**Issue by nishantrai18** [raokrutarth/manufacturing-os#47]
Task is to add support for manipulation of raftos containers. Complex objects would require custom JSON encoders. We'll also create simple interfaces which hide the complexities underneath them.

**Comment by nishantrai18** [comment]
Implemented the above. Currently seeing raftos.get_leader() = None on master, discovered it while testing these changes. 

@AndrejSafundzic @chuanqichen @raokrutarth any idea what's going on?

**Comment by raokrutarth** [comment]
will be closed once PR #48 merges.
