### ISSUE TITLE
Data representation in-memory/on-wire

### ISSUE THREAD

**Issue by raokrutarth** [raokrutarth/manufacturing-os#5]
@nishantrai18

**Comment by raokrutarth** [comment]
description of task: how will data be persisted by each process so it can handle resrarts?

Json 
- corruption during restart.

WAL 
- versioning of parts? 
- I.e. what if a new field needs to be added to the representation of a part.
  - needed only during migration?

**Comment by raokrutarth** [comment]
task: what does a part look like in memory and when communicated via network.

e.g. JSON object vs. python class vs. data structure.

Then, this object gets converted to bytes/compressed/protobuf when appending to a log.

**Comment by raokrutarth** [comment]
Business Class? Part Class? How will this interact with the WAL library? 

Table object in memory:
- may be flushed out to disk automatically?
- How does this survive process restarts?
- Does the table object have a WAL?

**Comment by nishant** [comment]
please mention the correct nishant via @nishantrai18.

**Comment by raokrutarth** [comment]
defined here: https://raw.githubusercontent.com/raokrutarth/manufacturing-os/master/src/processes.py
