### ISSUE TITLE
Determine if inter-node communication state needs to be stored

### ISSUE THREAD

**Issue by raokrutarth** [raokrutarth/manufacturing-os#51]

**Comment by raokrutarth** [comment]
this question is: if one node said X and another node said Y, but a crash occurred before the node exchange was completed (e.g. message W was not sent by node 1), do the nodes need to log the messages they have already sent?

**Comment by chuanqichen** [comment]
> this question is: if one node said X and another node said Y, but a crash occurred before the node exchange was completed (e.g. message W was not sent by node 1), do the nodes need to log the messages they have already sent?

@raokrutarth @nishantrai18 @AndrejSafundzic  In the real world situation, when one Node X (plant) sends out a batch of product to another Node (plant) Y through a transportation operation (we can simulate the duration for example 5 minutes), in between if Node (Plant) Y crashes, then where does the product go?   Go back to Node X, right? 

It seems that we can have this as enhancement feature to save inter-node communication state. What do you think?

**Comment by raokrutarth** [comment]
answer: node level logging is going to take care of logging the stage of item transition.
