### ISSUE TITLE
Advanced Flows + Tests

### ISSUE THREAD

**Issue by AndrejSafundzic** [raokrutarth/manufacturing-os#56]
1. Create Function that outputs one Flow

2. Add a test case like this as well,
"""
initialize demo_node with the following dependencies
start -> | -> 1 -> | -> 3 | -> 5
         | -> 2 -> | -> 4
"""
# All item reqs here involve 1 unit of product. So we have redundant sources of materials.
demo_nodes[0].dependency = items.ItemDependency([], [start])
demo_nodes[1].dependency = items.ItemDependency([start], [wood, screws])
demo_nodes[2].dependency = items.ItemDependency([start], [wood, screws])
demo_nodes[3].dependency = items.ItemDependency([wood, screws], [basic_door])
demo_nodes[4].dependency = items.ItemDependency([wood, screws], [premium_door])
demo_nodes[5].dependency = items.ItemDependency([basic_door, premium_door], [awesomeness])

3. Create another more complex algorithm flow

**Comment by nishantrai18** [comment]
```
"""
initialize demo_node with the following dependencies
0 -> | 1 | 4 | -> 6
     | 2 | 5 |
     | 3 |
"""

# All item reqs here involve 1 unit of product. So we have redundant sources of materials.

demo_nodes[0].dependency = items.ItemDependency([], [start])
demo_nodes[1].dependency = items.ItemDependency([start], [wood])
demo_nodes[2].dependency = items.ItemDependency([start], [wood])
demo_nodes[3].dependency = items.ItemDependency([start], [wood])
demo_nodes[4].dependency = items.ItemDependency([wood], [screws])
demo_nodes[5].dependency = items.ItemDependency([wood], [screws])
demo_nodes[6].dependency = items.ItemDependency([screws], [awesomeness])
```

**Comment by raokrutarth** [comment]
Still waiting for the graph restructure algorithm so we can simulate node deaths and see the restructure.

**Comment by AndrejSafundzic** [comment]
Done.
