### ISSUE TITLE
in-transit item log post crash

### ISSUE THREAD

**Issue by raokrutarth** [raokrutarth/manufacturing-os#64]
after a node crashes and comes back on, for all items it considered in-transit, it checks with neighbors if they were delivered before enqueuing to the SC stage.

**Comment by raokrutarth** [comment]
After node crash logic in implemented.

**Comment by raokrutarth** [comment]
@chuanqichen and @raokrutarth will wrap this up together tomorrow.

**Comment by raokrutarth** [comment]
I'm going to start this on sat morning

**Comment by raokrutarth** [comment]
I'm taking over this task from @chuanqichen

**Comment by chuanqichen** [comment]
Sure
