### ISSUE TITLE
Explore whether Krutarth's async example works with NodeProcess; integrate if possible

### ISSUE THREAD

**Issue by nishantrai18** [raokrutarth/manufacturing-os#72]
https://github.com/raokrutarth/manufacturing-os/blob/async-how-to/src/async_how_to.py

Was facing issues with a similar approach earlier; explore the new fixes krutarth has suggested. Ask for help otherwise :p

**Comment by raokrutarth** [comment]
Do you mean calling the methods below in different processes?

![image](https://user-images.githubusercontent.com/8570223/82494926-2cc7f180-9a9f-11ea-9513-983b0ad57f76.png)

**Comment by raokrutarth** [comment]
I can do that as part of my upcoming PR. Actually, I started and then saw this. or maybe you meant something else in this issue?

**Comment by raokrutarth** [comment]
@nishantrai18 please see if you can make the change in a way I can use it in a unittest. i.e. have a cluster.start() function. 

![image](https://user-images.githubusercontent.com/8570223/82553193-6d178600-9b18-11ea-9495-b8d35eda8839.png)

**Comment by nishantrai18** [comment]
Raftos was buggy
