### ISSUE TITLE
Add orchestrator to for node crashes

### ISSUE THREAD

**Issue by nishantrai18** [raokrutarth/manufacturing-os#77]
Add operations to OpHandler, nodes will automatically execute the request.
We need to add an entity that adds those operations in the OpHandlerQueue.

**Comment by raokrutarth** [comment]
This is the algorithm we decided on for killing nodes:

- DO NOT kill nodes randomly. Use the interractive client to send `kill_node(<node_id>)` command. Random crashes will made the demo difficult to follow.
- Above call in the interactive client will send a `Crash` message to the given node and the given node's operations handler thread will call `.stop()` on all the node's other threads.
- The `.stop()` call on the `sc_stage`, `publisher` will pause the thread's loop and set all in-memory data structures to `None`.
- From here on, the neighbors of the crashed node will tell the leader to restructure the flow.


Restart Workflow:
- The interactive client will call `restart_node(<node id>)` and the given node's operations thread will call `.start()` on all the threads of that node.
- the `start()` call will initialize all in-memory data structures to empty (e.g. `[]` for an array, `Queue()` for a thread safe queue, etc.).


The thread loops can be controlled via the [Event](https://docs.python.org/3.5/library/threading.html#event-objects) API.

**Comment by raokrutarth** [comment]
@nishantrai18 @AndrejSafundzic please confirm the above with an ack

**Comment by raokrutarth** [comment]
remove random crashes and keep operations thread running.

**Comment by raokrutarth** [comment]
may not need to use the event api. test the boolean flags to start/stop the thread loops.
