### ISSUE TITLE
Add support to measure cluster-wide, node-specific stats

### ISSUE THREAD

**Issue by nishantrai18** [raokrutarth/manufacturing-os#78]
Up to krutarth to figure out the exact details.

**Comment by raokrutarth** [comment]
Will implement a Metrics class that nodes can use in a ad-hoc fashion to persist metrics

**Comment by raokrutarth** [comment]
Metrics to be measured:

- number of messages sent & received by a node.
- Time taken to recognize leader.
- Time taken to get response of heartbeat from neighbors.
- size of payloads exchanged.
