### ISSUE TITLE
correct node id computation

### ISSUE THREAD

**Issue by raokrutarth** [raokrutarth/manufacturing-os#97]
tried with 50 nodes on server, flows were empty. issue could be here:

![image](https://user-images.githubusercontent.com/8570223/83727589-2a66ab00-a5fa-11ea-80b3-6425268a0042.png)

**Comment by raokrutarth** [comment]
`origin/stage-recovery`

**Comment by AndrejSafundzic** [comment]
Different node_ids for all nodes #100
